### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lgatto** [lgatto/tidies#1]
## Functions
- [ ] slice
- [ ] rename
- [ ] mutate

## Package 
- [ ] Unit tests
- [ ] Travis CI

**Comment by robertamezquita** [comment]
Making this work with `SummarizedExperiment` would be very exciting indeed, as there's a lot of development happening on Bioc around se (and, downstream, with `SingleCellExperiment`) objects!

**Comment by demar01** [comment]
Hi Laurent, is this project still ongoing? I contributed to some functions. This work would be greatly beneficial for my own research and others.

**Comment by lgatto** [comment]
I am not going to further develop this package, given that most of my work has moved to using `SummarizedExperiment` objects. There are several efforts for tidy analysis for the latter (for example [tidySummarizedExperiment](https://www.bioconductor.org/packages/release/bioc/html/tidySummarizedExperiment.html)) that will hopefully save me some time.

**Comment by demar01** [comment]
Hi Laurent
Thanks so much for pointing to that project. Cheers!



________________________________
